"""Build ping test"""
Import('ENV PREREQS')

TENV = ENV.Clone()
PREREQS.require(TENV, "pmix", "mercury", "bmi")
TENV.Append(CFLAGS=['-D_FILE_OFFSET_BITS=64'])
TENV.Prepend(CPPPATH=['../common/include'])
COMMON = TENV.Object('rpc_common')
COMMON += TENV.Object('rpc_handler')
COMMON += TENV.Object('server_backend')

if ENV['PLATFORM'] == 'darwin':
    TENV.Append(CFLAGS=['-I/usr/local/include/osxfuse'],
                LIBS=['osxfuse'])
else:
    TENV.Append(LIBS=['fuse', 'pthread'])

TENV.Program(['client_main.c', COMMON],
             LIBS=['$LIBS', 'proto_common'],
             LIBPATH=['$LIBPATH', '../common'])
TENV.Program(['server_main.c', COMMON],
             LIBS=['$LIBS', 'proto_common'],
             LIBPATH=['$LIBPATH', '../common'])
