"""install test scripts"""

TESTSCRIPTS = ["iof_test_fs.py", "iof_test_ionss.py"]

def scons():
    """Run scons"""

    Import('env')

    for script in TESTSCRIPTS:
        env.Install("$PREFIX/TESTING/scripts", script)
    # move the testing config files (.yml) to the TESTING scrpits directory
    env.Install("$PREFIX/TESTING/scripts", Glob("*.yml"))

if __name__ == 'SCons.Script':
    scons()

