"""Build ping test"""
Import('ENV PREREQS')

TENV = ENV.Clone()
TENV.Prepend(CPPPATH=['../common/include'])
PREREQS.require(TENV, "pmix", "mercury", "bmi")
COMMON = TENV.Object('my_rpc_common')

TENV.Program(['test_rpc_client.c', COMMON],
             LIBS=['$LIBS', 'proto_common'],
             LIBPATH=['$LIBPATH', '../common'])
TENV.Program(['test_rpc_server.c', COMMON])
