"""Build ping test"""
Import('ENV PREREQS')

TENV = ENV.Clone()
PREREQS.require(TENV, "pmix", "mercury", "bmi")
COMMON = TENV.Object('my_rpc_common')

TENV.Program(['test_rpc_client.c', COMMON])
TENV.Program(['test_rpc_server.c', COMMON])
