"""Build ping test"""
import os

def scons():
    """Scons function"""


    Import('env prereqs')

    tenv = env.Clone()
    prereqs.require(tenv, "mercury")

    libcommon = tenv.SharedLibrary(target='proto_common',
                                   source=['proto_common.c'])

    tenv.Install(os.path.join("$PREFIX", 'lib'), libcommon)
    tenv.Install(os.path.join("$PREFIX", 'include'), 'include/proto_common.h')

if __name__ == "SCons.Script":
    scons()
