"""Build ping test"""
import os
Import('ENV PREREQS')

TENV = ENV.Clone()
PREREQS.require(TENV, "mercury")

LIBCOMMON = TENV.SharedLibrary(target='proto_common', source=['proto_common.c'])

TENV.Install(os.path.join("$PREFIX", 'lib'), LIBCOMMON)
TENV.Install(os.path.join("$PREFIX", 'include'), 'include/proto_common.h')
