"""Build ping test"""
Import('ENV PREREQS')
import os

TENV = ENV.Clone()
PREREQS.require(TENV, "mercury")

LIBCOMMON = TENV.SharedLibrary(['proto_common.c'])

TENV.Install(os.path.join("$PREFIX", 'lib'), LIBCOMMON)
TENV.Install(os.path.join("$PREFIX", 'include'), 'include/proto_common.h')
