
Import('env all_deps')

tenv = env.Clone()
tenv.Append(LIBS=all_deps.get_libs("pmix") + all_deps.get_libs("mercury"))
tenv.Append(CFLAGS=['-g', '-Wall'])
common = tenv.Object('my_rpc_common')
sources = Glob('test*.c')

for source in sources:
    tenv.Program([source, common])
